<template>
  <div class="container mx-auto px-4 mt-8">
    <h1 class="text-3xl pb-3">Vue Palette Builder</h1>
    <p class="pb-8">
      Vue Palette Builder is a VueJS component for creating color palettes. Create a selection of colors using <a href="https://github.com/xiaokaike/vue-color">vue-color</a> picker, and get an array of color values.
    </p>
    <div class="my-4"><a href="#demo" class="mr-4">Demo</a> <a href="#output" class="mx-4"> Output</a> <a href="#installation" class="mx-4">Installation</a></div>
    <h2 class="text-3xl pb-3" id="#demo">Demo</h2>
    <div class="flex flex-col sm:flex-row justify-between items-start">
      <PaletteBuilder 
        v-on:get-palette="palette = $event"
        :pickerType="selectedPicker"
        id="colorpicker"
        class="pb-8 w-full max-w-sm"
      />
      <div class="inline-block relative w-64">
        <select v-model="selectedPicker" class="block appearance-none w-full bg-white border border-gray-400 hover:border-gray-500 px-4 py-2 pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline">
          <template v-for="picker in pickerType">
            <option :value="picker">{{picker}}</option>
          </template>
        </select>  
        <div class="pointer-events-none absolute inset-y-0 right-0 top-0 flex items-center px-2 text-gray-700">
          <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
        </div>

      </div>      

    </div>

    <h2 class="text-3xl pb-3" id="#output">Output</h2>
    <p class="pb-8">Vue Palette Builder outputs an array of objects that contain a variety of different color formats, such as Hex and RGBA. Here is the output generated by the current selection in the demo above.</p>
    <pre class="h-64 overflow-scroll bg-gray-200 pb-8 w-full">{{palette}}</pre>
    <p class="pb-3 pt-3">You can use these results to do whatever you want. This is an HTML canvas with a gradient of the colors selected in the Palette Builder. </p>

    <canvas id="canvas" width="400"></canvas>    
    <h2 class="text-3xl pb-3 pt-8" id="installation">Installation</h2>
    <p class="pb-3">Install on the command line with: </p>
    <pre class="bg-gray-200 p-2 mb-3 overflow-scroll">npm i vue-palette-builder</pre>
    <p class="pb-3">Import the component in your Vue app:</p>
    <pre class="bg-gray-200 p-2 mb-3 overflow-scroll">
import PaletteBuilder from 'vue-palette-builder' // import the component

export default {
  components: {
    PaletteBuilder // register the component
  },
  data() { 
    return {
      palette: [] // create a variable called "palette" to hold the output
    }
  }
}
    </pre>
    <p class="pb-3">Add the component to your markup:</p>
    <pre class="bg-gray-200 p-2 mb-3 overflow-scroll">
      {{componentHtml}}
    </pre>
    <p class="pb-3">Now the "palette" variable holds the output of whatever palette is built.</p>

    <p class="pb-3">The color picker is provided by <a href="https://github.com/xiaokaike/vue-color">Vue-color</a>. The options available are: Material, Compact, Swatches, Slider, Sketch, and Chrome.</p>
    <hr class="my-16"/>
    <p class="mb-16">Vue Palette Builder was built by <a href="https://alexharris.online">Alex Harris</a>  </p>
 
  </div>

</template>

<script>

const tailwind = require('tailwindcss');
import PaletteBuilder from 'vue-palette-builder'

export default {
  name: 'app',
  components: {
    PaletteBuilder
  },
  data() { 
    return {
      palette: [],
      pickerType: ['Chrome', 'Material', 'Compact', 'Swatches', 'Slider', 'Sketch'],
      selectedPicker: 'Chrome',
      componentHtml: `
<PaletteBuilder 
  v-on:get-palette="palette = $event"
  pickerType="Chrome"
/>`  
    }
  },
  watch: {
    palette: function() {
      this.buildCanvas()
    }
  },
  mounted() {
    this.buildCanvas()     
  },
  methods: {
    buildCanvas() {
        var canvas = document.getElementById('canvas');
        var ctx = canvas.getContext('2d');

        // Create a linear gradient
        // The start gradient point is at x=20, y=0
        // The end gradient point is at x=220, y=0
        var gradient = ctx.createLinearGradient(0,0, 400,0);

        // Add three color stops
        this.palette.forEach((v, i) => {
          console.log(i, this.palette.length)
          var position = (i + 1) / (this.palette.length + 1)
          gradient.addColorStop(position, v['hex8']);
        })
        
        // Set the fill style and draw a rectangle
        ctx.fillStyle = gradient;
        ctx.fillRect(0, 0, 400, 400);      
    }
  }
}
</script>

<style scoped>

@tailwind base;
@tailwind components;
@tailwind utilities;

a {
  @apply text-red-700 underline
}

p {
  @apply mb-3
}

/* #colorpicker {
  width: 400px;
} */
</style>

